function conduct_extrinsic_test_impl(U, golden_paraphrase_map, word, ...
                                     ppdb_paraphrase_rating, id)
fprintf(1, 'The MRR (1 indexed) over %s is %f\n', ...
        id, find_mrr(U, golden_paraphrase_map, word));
C1 = U(ppdb_paraphrase_rating(:,1),:);
C2 = U(ppdb_paraphrase_rating(:,2),:);
cosine_sim = sum(C1.*C2, 2);
kc=corr(cosine_sim, ppdb_paraphrase_rating(:,3), 'type', ...
             'Kendall');
fprintf(1, 'The Kendall Tau over %s is %f\n', id, kc);
fprintf(1, 'The Swapped Pair rate is %f in percentage\n', ((1-kc)/2)*100);
fprintf(1, 'The Pearson Corr over %s is %f\n', ...
        id, corr(cosine_sim, ppdb_paraphrase_rating(:,3), 'type', ...
             'Pearson'));
%fprintf(1, 'The Logistic Fit is %f\n', logistic_fit());